apiVersion: apps/v1
kind: Deployment
metadata:
  name: myInfo
  labels:
    app: myInfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myInfo
  template:
    metadata:
      labels:
        app: myInfo
    spec:
      containers:
        - name: myInfo
          image: skccuser10.azurecr.io/myInfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5